[package]
name = "lenient"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
lenient_derive = { path = "../lenient_derive" }
serde_json = "1.0.140"