[package]
name = "lenient_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
serde_json = "1.0.140"
lenient = { path = "../lenient" }